In [0]:

name = input('What is your name?   ')
if name != 'dasha':
  print('Say what?')
else:
  print('Good day', name)
  
  dict = {'First Name': 'dasha', 'Second Name': 'Clare'}
  choose = input('Show Values?  ')
  if choose == 'show':
    print(dict.values())
   

What is your name?   dasha
Good day dasha
Show Values?  show
dict_values(['dasha', 'Clare'])


In [0]:
import numpy as np


a = np.ones([2,2])
print (a)

randArray = np.random.randint(10, size=(5))
randArray1 = np.random.random([2,2])
print(randArray)

x = np.array([1,2,3])
y = np.array([4,5,6])
print('add ')
print(np.add(x,y))
print('Subtract')
print(np.subtract(x,y))
print('divide')
print(np.divide(x,y))


print('matrix multiply')
print(np.dot(x,y))
for num in x:
  print(num, end='') 
  
print('\n')
#   compute sum of all elements
print(np.sum(x))
# each col
print(np.sum(x, axis=0))
# each row
# print(np.sum(x, axis=1))

print('\n')
# copare
print(x>y)
print(x==y)
print(np.equal(x,y))

# np.argmax for index something


print(np.sqrt(x))



[[1. 1.]
 [1. 1.]]
[3 9 1 7 5]
add 
[5 7 9]
Subtract
[-3 -3 -3]
divide
[0.25 0.4  0.5 ]
matrix multiply
32
123

6
6


[False False False]
[False False False]
[False False False]
[1.         1.41421356 1.73205081]


# New Section