In [8]:
import numpy as np

A = np.array([[22, 13, 5,16],[13, 20, 19, 0],[5, 9, 1, 16], [27,13, 15, 19]])
B = np.array([[10, 5, 20, 20], [5, 21, 22, 27], [26, 19, 22, 3], [27, 8, 18, 7]])
c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])

print('number 1')
print(A+B)


number 1
[[32 18 25 36]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]


In [9]:
print('number 2')
print(A-B)


number 2
[[ 12   8 -15  -4]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]


In [10]:
print('number 3')
print(A*B)


number 3
[[220  65 100 320]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]


In [11]:
print('number 4')
print(np.dot(A,B))


number 4
[[ 847  606 1124  918]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]


In [12]:
print('number 5')
print(c+d)

number 5
[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]


In [13]:
print('number 6')
print(c-d)

number 6
[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]


In [15]:
print('number 7')
print(c*d)

number 7
[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]


In [22]:
print('number 8')
print(np.dot(c,d))

number 8
2298


In [18]:
print('number 9')
print(A + 10)

number 9
[[32 23 15 26]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]


In [19]:
print('number 10')
print(B-10)

number 10
[[ 0 -5 10 10]
 [-5 11 12 17]
 [16  9 12 -7]
 [17 -2  8 -3]]


In [20]:
print('number 11')
print(c+15)

number 11
[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]


In [24]:
print('number 12')
print(d+15)

number 12
[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]


In [25]:
print('number 13')
print((2*A) + (2 * B))

number 13
[[ 64  36  50  72]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [26]:
print('number 14')
print((A + B) * 3)

number 14
[[ 96  54  75 108]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]


In [29]:
print('number 15')
print((A-B + A-B + B) * 4)

number 15
[[ 136   84  -40   48]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]
